# Sysdig Secure — Azure Single Subscription Onboarding
#
# Generated by Sysdig Onboarding Skill
# Provider: Azure | Scope: Single Subscription
#
# Instructions:
#   1. Replace all {{PLACEHOLDER}} values with your actual values
#   2. Remove any feature sections you don't need (between === markers)
#   3. Run: export SYSDIG_SECURE_API_TOKEN="<your-token>"
#   4. Run: az login --tenant "{{AZURE_TENANT_ID}}"
#   5. Run: terraform init && terraform plan && terraform apply

terraform {
  required_version = ">= 1.10.0"
  required_providers {
    sysdig = {
      source  = "sysdiglabs/sysdig"
      version = "~> 3.3"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.76.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = ">= 2.43.0"
    }
  }
}

# --- Providers ---

provider "sysdig" {
  sysdig_secure_url       = "{{SYSDIG_SECURE_URL}}"
  sysdig_secure_api_token = var.sysdig_secure_api_token
}

provider "azurerm" {
  features {}
  subscription_id = "{{AZURE_SUBSCRIPTION_ID}}"
  tenant_id       = "{{AZURE_TENANT_ID}}"
}

provider "azuread" {
  tenant_id = "{{AZURE_TENANT_ID}}"
}

# --- Onboarding (always required) ---
# Registers this Azure subscription with Sysdig Secure and creates
# a Sysdig service principal with limited permissions.

module "onboarding" {
  source          = "sysdiglabs/secure/azurerm//modules/onboarding"
  subscription_id = "{{AZURE_SUBSCRIPTION_ID}}"
  tenant_id       = "{{AZURE_TENANT_ID}}"
}

# === CSPM (Cloud Security Posture Management) ===
# Assigns Reader role + custom role to the Sysdig service principal
# for resource discovery and compliance evaluation.

module "config-posture" {
  source                   = "sysdiglabs/secure/azurerm//modules/config-posture"
  subscription_id          = "{{AZURE_SUBSCRIPTION_ID}}"
  sysdig_secure_account_id = module.onboarding.sysdig_secure_account_id
}

resource "sysdig_secure_cloud_auth_account_feature" "config_posture" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_CONFIG_POSTURE"
  enabled    = true
  components = [module.config-posture.config_posture_component_id]
  depends_on = [module.config-posture]
}

# === END CSPM ===

# === CIEM Basic (Cloud Identity & Entitlement Management) ===
# Analyzes IAM roles and policies for overly permissive access.
# Uses the same posture data as CSPM — no additional infrastructure.
# NOTE: Keep this block even when enabling CIEM Advanced — advanced
# builds on top of basic via concat() on its components.

resource "sysdig_secure_cloud_auth_account_feature" "identity_entitlement_basic" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_IDENTITY_ENTITLEMENT"
  enabled    = true
  components = [module.config-posture.config_posture_component_id]
  depends_on = [module.config-posture, sysdig_secure_cloud_auth_account_feature.config_posture]
  flags = {
    "CIEM_FEATURE_MODE" : "basic"
  }

  lifecycle {
    ignore_changes = [flags, components]
  }
}

# === END CIEM Basic ===

# === CDR (Cloud Detection & Response) ===
# Creates an Event Hub namespace + diagnostic settings for streaming
# Azure Activity Logs and Entra ID logs for threat detection.

module "event-hub" {
  source                   = "sysdiglabs/secure/azurerm//modules/integrations/event-hub"
  subscription_id          = "{{AZURE_SUBSCRIPTION_ID}}"
  region                   = "{{AZURE_REGION}}"
  sysdig_secure_account_id = module.onboarding.sysdig_secure_account_id
}

resource "sysdig_secure_cloud_auth_account_feature" "threat_detection" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_THREAT_DETECTION"
  enabled    = true
  components = [module.event-hub.event_hub_component_id]
  depends_on = [module.event-hub]
}

# === END CDR ===

# === CIEM Advanced (upgrades CIEM Basic) ===
# Least-privilege analysis based on actual usage patterns.
# Requires BOTH config-posture AND event-hub data.
# NOTE: Requires the CIEM Basic block above — advanced uses concat()
# to build on basic's components.

resource "sysdig_secure_cloud_auth_account_feature" "identity_entitlement_advanced" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_IDENTITY_ENTITLEMENT"
  enabled    = true
  components = concat(
    tolist(sysdig_secure_cloud_auth_account_feature.identity_entitlement_basic.components),
    [module.event-hub.event_hub_component_id]
  )
  depends_on = [
    module.event-hub,
    module.event-hub.post_ciem_basic_delay
  ]
  flags = { "CIEM_FEATURE_MODE" : "advanced" }

  lifecycle {
    ignore_changes = [flags, components]
  }
}

# === END CIEM Advanced ===

# === VM (Vulnerability Management — Agentless Scanning) ===
# Scans VMs and container images via Azure Lighthouse for
# cross-subscription disk snapshot access.

module "agentless-scanning" {
  source                   = "sysdiglabs/secure/azurerm//modules/agentless-scanning"
  subscription_id          = "{{AZURE_SUBSCRIPTION_ID}}"
  sysdig_secure_account_id = module.onboarding.sysdig_secure_account_id
}

resource "sysdig_secure_cloud_auth_account_feature" "agentless_scanning" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_AGENTLESS_SCANNING"
  enabled    = true
  components = [module.agentless-scanning.service_principal_component_id]
  depends_on = [module.agentless-scanning]
}

# === END VM ===
