# Sysdig Secure — GCP Single Project Onboarding
#
# Generated by Sysdig Onboarding Skill
# Provider: GCP | Scope: Single Project
#
# Instructions:
#   1. Replace all {{PLACEHOLDER}} values with your actual values
#   2. Remove any feature sections you don't need (between === markers)
#   3. Run: export SYSDIG_SECURE_API_TOKEN="<your-token>"
#   4. Run: terraform init && terraform plan && terraform apply

terraform {
  required_version = ">= 1.10.0"
  required_providers {
    sysdig = {
      source  = "sysdiglabs/sysdig"
      version = "~> 3.3"
    }
    google = {
      source  = "hashicorp/google"
      version = ">= 4.21.0"
    }
  }
}

# --- Providers ---

provider "sysdig" {
  sysdig_secure_url       = "{{SYSDIG_SECURE_URL}}"
  sysdig_secure_api_token = var.sysdig_secure_api_token
}

provider "google" {
  project = "{{GCP_PROJECT_ID}}"
  region  = "{{GCP_REGION}}"
}

# --- Onboarding (always required) ---
# Registers this GCP project with Sysdig Secure and creates
# service accounts + workload identity pools.

module "onboarding" {
  source     = "sysdiglabs/secure/google//modules/onboarding"
  project_id = "{{GCP_PROJECT_ID}}"
}

# === CSPM (Cloud Security Posture Management) ===
# Creates a service account with viewer roles for resource inventory
# and compliance evaluation.

module "config-posture" {
  source                   = "sysdiglabs/secure/google//modules/config-posture"
  project_id               = "{{GCP_PROJECT_ID}}"
  sysdig_secure_account_id = module.onboarding.sysdig_secure_account_id
}

resource "sysdig_secure_cloud_auth_account_feature" "config_posture" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_CONFIG_POSTURE"
  enabled    = true
  components = [module.config-posture.service_principal_component_id]
  depends_on = [module.config-posture]
}

# === END CSPM ===

# === CIEM Basic (Cloud Identity & Entitlement Management) ===
# Analyzes IAM roles and policies for overly permissive access.
# Uses the same posture data as CSPM — no additional infrastructure.
# NOTE: Keep this block even when enabling CIEM Advanced — advanced
# builds on top of basic via concat() on its components.

resource "sysdig_secure_cloud_auth_account_feature" "identity_entitlement_basic" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_IDENTITY_ENTITLEMENT"
  enabled    = true
  components = [module.config-posture.service_principal_component_id]
  depends_on = [module.config-posture, sysdig_secure_cloud_auth_account_feature.config_posture]
  flags = {
    "CIEM_FEATURE_MODE" : "basic"
  }

  lifecycle {
    ignore_changes = [flags, components]
  }
}

# === END CIEM Basic ===

# === CDR (Cloud Detection & Response) ===
# Forwards audit logs via Pub/Sub PUSH subscription for real-time
# threat detection.

module "pub-sub" {
  source                   = "sysdiglabs/secure/google//modules/integrations/pub-sub"
  project_id               = "{{GCP_PROJECT_ID}}"
  sysdig_secure_account_id = module.onboarding.sysdig_secure_account_id
}

resource "sysdig_secure_cloud_auth_account_feature" "threat_detection" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_THREAT_DETECTION"
  enabled    = true
  components = [module.pub-sub.pubsub_datasource_component_id]
  depends_on = [module.pub-sub]
}

# === END CDR ===

# === CIEM Advanced (upgrades CIEM Basic) ===
# Least-privilege analysis based on actual usage patterns.
# Requires BOTH config-posture AND pub-sub data.
# NOTE: Requires the CIEM Basic block above — advanced uses concat()
# to build on basic's components.

resource "sysdig_secure_cloud_auth_account_feature" "identity_entitlement_advanced" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_IDENTITY_ENTITLEMENT"
  enabled    = true
  components = concat(
    tolist(sysdig_secure_cloud_auth_account_feature.identity_entitlement_basic.components),
    [module.pub-sub.pubsub_datasource_component_id]
  )
  depends_on = [
    module.pub-sub,
    module.pub-sub.post_ciem_basic_delay
  ]
  flags = { "CIEM_FEATURE_MODE" : "advanced" }

  lifecycle {
    ignore_changes = [flags, components]
  }
}

# === END CIEM Advanced ===

# === VM (Vulnerability Management — Agentless Scanning) ===
# Scans compute instances and container images for vulnerabilities.

module "agentless-scan" {
  source                   = "sysdiglabs/secure/google//modules/agentless-scan"
  project_id               = "{{GCP_PROJECT_ID}}"
  sysdig_secure_account_id = module.onboarding.sysdig_secure_account_id
}

resource "sysdig_secure_cloud_auth_account_feature" "agentless_scanning" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_AGENTLESS_SCANNING"
  enabled    = true
  components = [module.agentless-scan.agentless_scan_component_id]
  depends_on = [module.agentless-scan]
}

# === END VM ===
