# Sysdig Secure — AWS Organization Onboarding
#
# Generated by Sysdig Onboarding Skill
# Provider: AWS | Scope: Organization (multi-account)
#
# Instructions:
#   1. Replace all {{PLACEHOLDER}} values with your actual values
#   2. Remove any feature sections you don't need (between === markers)
#   3. Run: export SYSDIG_SECURE_API_TOKEN="<your-token>"
#   4. Run: terraform init && terraform plan && terraform apply
#
# NOTE: Run this from the AWS Organization management account.
# Requires: IAMFullAccess, AWSOrganizationsReadOnlyAccess,
#           AWSCloudFormationFullAccess

terraform {
  required_version = ">= 1.10.0"
  required_providers {
    sysdig = {
      source  = "sysdiglabs/sysdig"
      version = "~> 3.3"
    }
    aws = {
      source  = "hashicorp/aws"
      version = ">= 6.0"
    }
  }
}

# --- Providers ---

provider "sysdig" {
  sysdig_secure_url       = "{{SYSDIG_SECURE_URL}}"
  sysdig_secure_api_token = var.sysdig_secure_api_token
}

provider "aws" {
  region = "{{AWS_REGION}}"

  # Account safety: Terraform will refuse to run if the active credentials
  # do not match this account ID. Prevents deploying to the wrong account.
  allowed_account_ids = ["{{AWS_ACCOUNT_ID}}"]

  # AWS CLI profile — ensures consistent credentials across CLI and Terraform.
  # Remove if using environment variables or instance roles instead.
  profile = "{{AWS_PROFILE}}"
}

# --- Onboarding (Organization) ---
# Registers the AWS Organization with Sysdig Secure.
# Deploys CloudFormation StackSets to member accounts.

module "onboarding" {
  source             = "sysdiglabs/secure/aws//modules/onboarding"
  is_organizational  = true

  # Filter which accounts to include/exclude (leave empty for all)
  include_ouids    = {{INCLUDE_OUIDS}}    # e.g., ["ou-xxxx-xxxxxxxx"]
  exclude_ouids    = {{EXCLUDE_OUIDS}}    # e.g., []
  include_accounts = {{INCLUDE_ACCOUNTS}} # e.g., []
  exclude_accounts = {{EXCLUDE_ACCOUNTS}} # e.g., ["123456789012"]

  # Auto-discover new accounts added to the organization
  enable_automatic_onboarding = {{ENABLE_AUTO_ONBOARDING}} # true or false
}

# === CSPM (Cloud Security Posture Management) ===

module "config-posture" {
  source                   = "sysdiglabs/secure/aws//modules/config-posture"
  sysdig_secure_account_id = module.onboarding.sysdig_secure_account_id
  is_organizational        = true

  include_ouids    = module.onboarding.include_ouids
  exclude_ouids    = module.onboarding.exclude_ouids
  include_accounts = module.onboarding.include_accounts
  exclude_accounts = module.onboarding.exclude_accounts
}

resource "sysdig_secure_cloud_auth_account_feature" "config_posture" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_CONFIG_POSTURE"
  enabled    = true
  components = [module.config-posture.config_posture_component_id]
  depends_on = [module.config-posture]
}

# === END CSPM ===

# === CIEM Basic (Cloud Identity & Entitlement Management) ===
# Analyzes IAM roles and policies for overly permissive access.
# Uses the same posture data as CSPM — no additional infrastructure.
# NOTE: Keep this block even when enabling CIEM Advanced — advanced
# builds on top of basic via concat() on its components.

resource "sysdig_secure_cloud_auth_account_feature" "identity_entitlement_basic" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_IDENTITY_ENTITLEMENT"
  enabled    = true
  components = [module.config-posture.config_posture_component_id]
  depends_on = [module.config-posture, sysdig_secure_cloud_auth_account_feature.config_posture]
  flags = {
    "CIEM_FEATURE_MODE" : "basic"
  }

  lifecycle {
    ignore_changes = [flags, components]
  }
}

# === END CIEM Basic ===

# === CDR (Cloud Detection & Response) ===

module "event-bridge" {
  source                   = "sysdiglabs/secure/aws//modules/integrations/event-bridge"
  sysdig_secure_account_id = module.onboarding.sysdig_secure_account_id
  is_organizational        = true

  regions = {{EVENT_BRIDGE_REGIONS}}

  include_ouids    = module.onboarding.include_ouids
  exclude_ouids    = module.onboarding.exclude_ouids
  include_accounts = module.onboarding.include_accounts
  exclude_accounts = module.onboarding.exclude_accounts
}

resource "sysdig_secure_cloud_auth_account_feature" "threat_detection" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_THREAT_DETECTION"
  enabled    = true
  components = [module.event-bridge.event_bridge_component_id]
  depends_on = [module.event-bridge]
}

# === END CDR ===

# === CDR_CLOUDLOGS (Cloud Detection & Response via CloudTrail/S3) ===
# Threat detection from CloudTrail logs stored in S3.
# Requires an EXISTING CloudTrail trail with S3 bucket and SNS topic.

provider "aws" {
  alias  = "sns"
  region = "{{SNS_TOPIC_REGION}}"  # Region where the SNS topic lives

  # Must match the default provider's account pinning.
  allowed_account_ids = ["{{AWS_ACCOUNT_ID}}"]
  profile             = "{{AWS_PROFILE}}"
}

module "cloud-logs" {
  source                   = "sysdiglabs/secure/aws//modules/integrations/cloud-logs"
  sysdig_secure_account_id = module.onboarding.sysdig_secure_account_id
  is_organizational        = true

  bucket_arn   = "{{CLOUDTRAIL_BUCKET_ARN}}"
  topic_arn    = "{{CLOUDTRAIL_SNS_TOPIC_ARN}}"
  create_topic = {{CREATE_SNS_TOPIC}}   # true if no existing SNS topic
  role_name    = "sysdig-secure-cloudlogs"

  # Uncomment if the S3 bucket uses KMS encryption:
  # kms_key_arn = "{{KMS_KEY_ARN}}"

  regions = {{CLOUD_LOGS_REGIONS}}

  include_ouids    = module.onboarding.include_ouids
  exclude_ouids    = module.onboarding.exclude_ouids
  include_accounts = module.onboarding.include_accounts
  exclude_accounts = module.onboarding.exclude_accounts

  providers = {
    aws     = aws
    aws.sns = aws.sns
  }
}

resource "sysdig_secure_cloud_auth_account_feature" "threat_detection" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_THREAT_DETECTION"
  enabled    = true
  components = [module.cloud-logs.cloud_logs_component_id]
  depends_on = [module.cloud-logs]
}

# === END CDR_CLOUDLOGS ===

# === CIEM Advanced (upgrades CIEM Basic) ===
# Least-privilege analysis based on actual usage patterns.
# Requires BOTH config-posture AND event-bridge data.
# NOTE: Requires the CIEM Basic block above — advanced uses concat()
# to build on basic's components.

resource "sysdig_secure_cloud_auth_account_feature" "identity_entitlement_advanced" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_IDENTITY_ENTITLEMENT"
  enabled    = true
  components = concat(
    tolist(sysdig_secure_cloud_auth_account_feature.identity_entitlement_basic.components),
    [module.event-bridge.event_bridge_component_id]
  )
  depends_on = [
    module.event-bridge,
    module.event-bridge.post_ciem_basic_delay
  ]
  flags = { "CIEM_FEATURE_MODE" : "advanced" }

  lifecycle {
    ignore_changes = [flags, components]
  }
}

# === END CIEM Advanced ===

# === CIEM_ADVANCED_CLOUDLOGS (upgrades CIEM Basic — CloudTrail/S3 variant) ===
# Least-privilege analysis based on actual usage patterns.
# Uses cloud-logs (CloudTrail/S3) instead of EventBridge for CDR data.
# NOTE: Requires the CIEM Basic block above — advanced uses concat()
# to build on basic's components.

resource "sysdig_secure_cloud_auth_account_feature" "identity_entitlement_advanced" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_IDENTITY_ENTITLEMENT"
  enabled    = true
  components = concat(
    tolist(sysdig_secure_cloud_auth_account_feature.identity_entitlement_basic.components),
    [module.cloud-logs.cloud_logs_component_id]
  )
  depends_on = [
    module.cloud-logs,
    module.cloud-logs.post_ciem_basic_delay
  ]
  flags = { "CIEM_FEATURE_MODE" : "advanced" }

  lifecycle {
    ignore_changes = [flags, components]
  }
}

# === END CIEM_ADVANCED_CLOUDLOGS ===

# === VM (Vulnerability Management — Agentless Scanning) ===

module "agentless-scanning" {
  source                   = "sysdiglabs/secure/aws//modules/agentless-scanning"
  sysdig_secure_account_id = module.onboarding.sysdig_secure_account_id
  is_organizational        = true

  regions = {{AGENTLESS_SCANNING_REGIONS}}

  include_ouids    = module.onboarding.include_ouids
  exclude_ouids    = module.onboarding.exclude_ouids
  include_accounts = module.onboarding.include_accounts
  exclude_accounts = module.onboarding.exclude_accounts
}

resource "sysdig_secure_cloud_auth_account_feature" "agentless_scanning" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_AGENTLESS_SCANNING"
  enabled    = true
  components = [
    module.agentless-scanning.scanning_role_component_id,
    module.agentless-scanning.crypto_key_component_id,
  ]
  depends_on = [module.agentless-scanning]
}

# === END VM ===

# === WORKLOAD_SCANNING (Vulnerability Management — ECS + Lambda) ===
# Scans container images in ECS and Lambda functions for vulnerabilities.
# Uses a separate module from Agentless Scanning (which covers EC2).

module "vm-workload-scanning" {
  source                   = "sysdiglabs/secure/aws//modules/vm-workload-scanning"
  sysdig_secure_account_id = module.onboarding.sysdig_secure_account_id
  is_organizational        = true

  # Enable Lambda function scanning in addition to ECS
  lambda_scanning_enabled = {{LAMBDA_SCANNING_ENABLED}}  # true or false

  include_ouids    = module.onboarding.include_ouids
  exclude_ouids    = module.onboarding.exclude_ouids
  include_accounts = module.onboarding.include_accounts
  exclude_accounts = module.onboarding.exclude_accounts
}

resource "sysdig_secure_cloud_auth_account_feature" "workload_scanning_containers" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_WORKLOAD_SCANNING_CONTAINERS"
  enabled    = true
  components = [module.vm-workload-scanning.vm_workload_scanning_component_id]
  depends_on = [module.vm-workload-scanning]
}

resource "sysdig_secure_cloud_auth_account_feature" "workload_scanning_functions" {
  account_id = module.onboarding.sysdig_secure_account_id
  type       = "FEATURE_SECURE_WORKLOAD_SCANNING_FUNCTIONS"
  enabled    = true
  components = [module.vm-workload-scanning.vm_workload_scanning_component_id]
  depends_on = [module.vm-workload-scanning]
}

# === END WORKLOAD_SCANNING ===
